title: Data Reviews Online
description: A web application for managing submissions to data repositories.
show_downloads: true
theme: jekyll-theme-slate
logo: assets/images/dareon.jpg
google_analytics: 